### ISSUE TITLE
[BUG] wrong package command in Svelte template

### ISSUE THREAD

**Issue by matthme** [holochain/scaffolding#110]
The `cd public` command in this [this](https://github.com/holochain/scaffolding/blob/21130bbab5adda281223d5bef53e108d7a4ccca5/templates/svelte/web-app/ui/package.json.hbs#L8) line of the Svelte template should be replace with `cd dist`. Otherwise it packages the wrong files into the .webhapp file.

**Comment by c12i** [comment]
Closing since this has now been fixed
