### ISSUE TITLE
[Enhancement] Allow specifying rev/tag/branch for templates

### ISSUE THREAD

**Issue by matthme** [holochain/scaffolding#122]
The [degit](https://crates.io/crates/degit) crate used to fetch the template when using the `--templates-url` argument does not allow to specify rev/tag/branch which is quite a bummer when a template is supposed to support multiple holochain versions.

**Comment by c12i** [comment]
I think it probably has to do with `degit` not supporting this, and the project seems to not have been updated in three years.

To support specifying the /rev/tag/branch, we could probably migrate to using the [`git2`](https://github.com/rust-lang/git2-rs) crate and cloning the repo using the [`RepoBuilder`](https://docs.rs/git2/latest/git2/build/struct.RepoBuilder.html), the degit the cloned repo by deleting the `.git` directory.

**Comment by c12i** [comment]
Closing this since the `--templates-url` option is no longer supported with much recent versions of hc-scaffold.
