### ISSUE TITLE
Two zomes in scaffold window produce one as an output

### ISSUE THREAD

**Issue by var-che** [holochain/scaffolding#13]
Hi
When I run the _npx @holochain/create@latest_ , I made two zomes within one DNA, but as an output, it created:
1. two integrity folders with files
2. only one conductor file, just for the first some. 

I have included the screenshot of it:
![Screenshot from 2022-08-15 17-06-47](https://user-images.githubusercontent.com/480649/184661944-0cd60a18-926c-4f45-bd15-b8fd5f8e9f9a.png)

**Comment by matthme** [comment]
Thank you for reporting, this has been fixed with #16.
