### ISSUE TITLE
Tests fail after creating scaffold app

### ISSUE THREAD

**Issue by var-che** [holochain/scaffolding#15]
Hi
Right after I create a scaffolded app via the _npx @holochain/create@latest_, I added another zome, so that I have two zones in the DNA, I start _nix-shell_, I run _npm test_, I get an error.

https://pastebin.com/3qmtFSsr

Edit;
This bug does not exist if you create the only one zome in the DNA.

**Comment by matthme** [comment]
Is this issue still present with the latest version?
