### ISSUE TITLE
Add a `--version` option to `hc-sandbox`

### ISSUE THREAD

**Issue by ddd-mtl** [holochain/scaffolding#152]
Since `hc-sandbox` is its own binary, and holochain has multiple versions developed in parallel it would help me to know what version `hc-sandbox` is when I encounter an error like `Error: Deserialize("wrong msgpack marker FixStr(5)")` when testing my happ.

**Comment by ThetaSinner** [comment]
Yes I ran into this the other day. `hc` gives you a version but `hc-sandbox` does not. I'm happy to add this, it's a straight forward change I believe.

This binary is built from the Holchain repository here https://github.com/holochain/holochain/tree/develop/crates/hc_sandbox. Would you be willing to open the issue over there and I'll take a look?

**Comment by ddd-mtl** [comment]
done. Didnt realize I was in scaffolding...
