### ISSUE TITLE
Tryorama error when tests are run

### ISSUE THREAD

**Issue by var-che** [holochain/scaffolding#17]
Hi

After installing and compiling the scaffolding app, I get the following error when I run the `npm test`.

https://pastebin.com/m3ZFjrEq

I know that the issue is dispatched to the right team, but this issue is a tracker for us who wants to see when that bug is fixed.

**Comment by matthme** [comment]
Thanks :). Issue is fixed now with the latest version. To update existing projects you can just change the version number of `@holochain/tryorama` in `tests/package.json` to the latest version `0.7.0` and run `npm install` in the root directory.
