### ISSUE TITLE
[BUG] hello-world example fails with "top-level await not available"

### ISSUE THREAD

**Issue by matthme** [holochain/scaffolding#193]
Error:
```
[vite:esbuild-transpile] Transform failed with 1 error:
assets/index-!~{001}~.js:9560:6: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 3 overrides)

Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 3 overrides)
9558|        window.getHellos = getHellos;
9559|  
9560|        await connect();
   |        ^

✓ built in 1.51s
```

Steps to reproduce:
Follow the steps in https://developer.holochain.org/get-started/ (section `3. Scaffold a simple “Hello, World!” Holochain application`)

**Comment by matthme** [comment]
I think the line `await connect();` in `index.html` needs to be replaced with `(async () => await connect())();`

**Comment by c12i** [comment]
@matthme which version did you test this out with? `0.2` or `0.1`?

**Comment by matthme** [comment]
I was following the steps on https://developer.holochain.org/get-started/ which are using holochain 0.1

**Comment by c12i** [comment]
Okay, I'll look into it, thanks for the find.

**Comment by matthme** [comment]
Oh sorry, I realized that I was not correct in my reproduction steps. `npm run start` works fine, it's `npm run package` that threw the error. But it's fixed with the PR anyway, thanks!
