### ISSUE TITLE
Custom templates refactor is needed

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/scaffolding#213]
The way that custom templates coming from some git repository are managed at the moment works but is really brittle. This is the main strokes of how it works:

1. When running `hc scaffold web-app`, you can pass an argument `--templates-url`, which must point to a git repository. The scaffolding tool will clone that repository and add the `.templates` folder of that repository to the `.templates` folder of the newly created app.
2. After that, every time `hc scaffold` is run, the scaffolding tool checks the `.templates` folder, and if it finds it, it will use that custom template to scaffold the command.

There are some problems with this:

- The template code is checked in the source code for the consumer apps for the template. This means that every time the template is updated, the developer of the app must run `hc scaffold template get` to redownload the template.
- If the scaffolding tool implements breaking changes, the template will be broken without the developer knowing about it, and they will have a really bad experience using the custom template.

The main intention behind custom templates is to enable flexibility on the frontend side for devs. The scaffolding tool can't really impose decisions around javascript frameworks, state management libraries, and UI component libraries to the whole ecosystem. Thus, I imagined, experienced developers are going to maintain their opinionated custom templates, and more beginner level devs that trust them are going to use their custom templates.

I have a proposal on how to refactor the custom templates handling to solve for this. After doing some investigation, [it is possible to create a flake that wraps hc-scaffold with a custom template and re-exports that](https://github.com/holochain-open-dev/templates/blob/fd0b60610d581f4be31f438355e3da59440f5091/flake.nix#L38). I love this solution because:

- It no longer requires devs to check the template within their repo.
- It hides the complexity of using a custom template.
- It is the template repository that decides which `hc-scaffold` version to use, and when they update that version, they should retest everything before publishing it.
- The consumers of the template can run `nix run github:holochain-open-dev/templates#hc-scaffold-app -- web-app` to scaffold a new app with the template.
- The consumers of the template get a new version of the template by simply running `nix flake update`. 

There are a few changes needed on the side of the scaffolding tool to enable this:

- Refactor the [`--templates-path`](https://github.com/holochain/scaffolding/blob/927cdb91efb7547b2236b593be1580a1c15bd699/src/cli.rs#L66) CLI argument so that _all commands accept it_.
- Remove all the code that reads and writes templates from `.templates`
- Remove `hc scaffold template get`, maybe `hc scaffold template init` is still good to have? Not sure about this last one.
- Reconsider whether `--templates-url` should still exist. The only use case I can think for this is non-nix users, but I already exposed all the problems I have with this argument.

@c12i what do you think?

**Comment by c12i** [comment]
I agree that the current requirement to run `hc scaffold template get` doesn't offer the best developer experience.

The idea of wrapping `hc-scaffold` with a custom template and letting the template dictate the version of scaffolding is promising, and scaffolding not able to accept the branch/tag/ref of the custom template makes this even harder to ensure the template and scaffolding versions are compatible. I'll delve into this further, as my Nix knowledge is still evolving, thanks for the example link you provided.

Some questions I have though:
- While I see the benefits of using Nix for this solution, do you think it's wise to lock this functionality behind Nix? I encountered a user in #138 who prefers using scaffolding outside of Nix. Perhaps retaining the `--templates-url` argument could be considered, even though it might mean potential roundtrip requests to the template for each command.
- Would `--templates-path` only be necessary for happs using custom templates? If users opt for a custom template, could you provide an example of how they might pass this path?
- I understand the need to require `--templates-path` for all commands, but I'm concerned about the potential impact on developer experience. Would it be worth considering a global environment variable i.e `TEMPLATES_PATH=` that users can set in advance to reference this path for future commands?
- Regarding `hc scaffold template init`, I believe its original purpose was to empower users to customize the inbuilt template or leverage code from these templates for their custom ones. For this use case, I think retaining this command is crucial.

Let me know what you think @guillemcordoba

**Comment by guillemcordoba** [comment]
Hey @c12i this is great, thanks. I'll answer your questions in order:

1. I'm fine with retaining the `--templates-url` argument, but without nix I don't have a proposal on how to have a good developer experience. Even if we mandate that that argument is passed in every command, the scaffolding tool may be updated independently of the template, which potentially breaks the template. Maybe a solution is for the template to declare the semver version of the scaffolding tool that it depends on, and the scaffolding tool checks that and throws an error if it doesn't match? Not sure. So for me the important point is that we _enable_ the kind of lockstep update between custom templates and the scaffolding tool I'm talking about. 
2. Yeah `--templates-path` would be optional and used to specify a custom template, for sure. If you don't provide it, the current behavior of the scaffolding tool is to use one of the built-in templates, which I think is a good default? 
3. That's the cool thing about the nix wrapper, the developer experience is really smooth. So, to use a custom template this way, these are the commands that the developer will need to run:
```
nix run github:holochain-open-dev/templates#hc-scaffold-app-template -- web-app someapp
cd someapp
nix develop
hc scaffold dna
hc scaffold zome
hc scaffold entry-type
```
Exactly the same experience as it is with the built-in templates from the scaffolding tool, _but it will scaffold the frontend in the way that the custom template determines_. So, as you see, the developer doesn't even know or have to care about the `--templates-path`, it is introduced in the wrapping that the custom template author wraps in the nix flake. This is also enabled by the `TEMPLATES_PATH` env var that you suggest, so I would be fine with that solution as well, although it doesn't seem as clean to me as the CLI argument.
4. Yeah `hc scaffold template init` seems important yeah, but we could potentially drop the other ones.

One last important point is that the way that templates are built, they assume that the same template is used from the start to end of the app development lifecycle. That is, you can't scaffold an app using the svelte template, and later on switch to the vue template - it will break because the vue template is trying to edit vue specific files that should have been scaffolded with the vue template in the first place. This is what I was trying to lock with the templates being checked in to source control, but I like the nix way even more - it's locked in the `hc scaffold` command that the nix develop shell provides.

**Comment by c12i** [comment]
@guillemcordoba sorry I am replying a little late, returning from absence last week.

> Maybe a solution is for the template to declare the semver version of the scaffolding tool that it depends on, and the scaffolding tool checks that and throws an error if it doesn't match?

Yes this is more logical, and predictable. This would be a good argument for retaining the `--templates-url` flag, with this extra step of checking whether the current version of scaffolding in use conflicts with that of the template. How could this this version be declared though, via some manifest file in the template repo?

> `nix run github:holochain-open-dev/templates#hc-scaffold-app-template -- web-app someapp`

This is indeed a looks like a much cleaner apporoach, I am assuming the nix flake would be defined in the template repo like you shared [here](https://github.com/holochain-open-dev/templates/blob/fd0b60610d581f4be31f438355e3da59440f5091/flake.nix#L38), right? Also I would like to believe that this command can also be run against templates sourced from other git hosts such as gitlab or bitbucket. I am asking this because there is currently an open issue regarding using `gitlab` urls with `--template-url` #197

> If you don't provide it, the current behaviour of the scaffolding tool is to use one of the built-in templates, which I think is a good default?

Yes this is good default behaviour

**Comment by c12i** [comment]
> This does feel like reinventing the server wheel in some sense without using cargo or nix or one of the well established package managers that already have all that logic built-in.

I understand, perhaps it would be better to rely on nix as you suggest to indicate the compatible scaffolding versions, and have this checked before scaffolding the happ. 

But this brings another question, how do we ensure that a custom template can be used with different versions of scaffolding? I noticed that there is a `0.1` compatible version of the open dev custom template in a separate branch, this is a pattern that would still be retained right?

**Comment by c12i** [comment]
> Yes, and yes. By leveraging nix, we automatically have all git hosts, plus versioning and upgrading at the right level, plus most apps already use nix. I'm very excited about this option!

Great! I have already been tinkering with the open-dev templates to see how this works at the moment, what I noticed is that the template gets downloaded to a `/tmp/nix-shell.ywczZT/t4e72-0` dir, but I also notice the `.templates` dir in the root of the scaffolded project is retained and still checked into git, from what I understood, this shouldn't be the case, unless I am missing something

**Comment by guillemcordoba** [comment]
This is the way it was designed to work, the template is supposed to be downloaded and checked in git. So there is no issue in its current functioning. What I'm suggesting is that this pattern should be refactored in the ways we've been talking.

**Comment by c12i** [comment]
Understood, I think I have a better understanding of how the suggested nix wrapper approach would be a valuable addition, open to having this as an option.

With regards to removing all the code that reads and writes templates from `.templates`, I think this would be tricky since the `--templates-url` workflow would still rely on this folder existing. 

I think if making sure what is downloaded template stays in sync with the what is in the git repo, then having the compatible version of scaffolding the template supports declared _somewhere on the repo_  or even the current semver version of the template itself, that can be checked against what's saved locally for the commands that interact with the `.templates` dir, then automatically providing a prompt to the user to auto update / skip updating their template would make it more transparent for them on when to update their template.

I have spent some time thinking how best to declare supported templates, we don't want a manifest file as stated before due to unnecessary complexity, we could keep things simple by having a simple `.scaffoldrc` file on the repo that stores this information in a preferred format to be determined. Then we can be making a http request to this specific raw file to check for compatibility, skipping this check if the request fails (incase the user is offline). Would like to hear your thoughts on this approach. I am not sure how we can achieve this via nix but I am open to hear your suggestions on this as well.

**Comment by c12i** [comment]
What I have suggested above still doesn't solve the issue of having to check the `.templates` folder into git though, but I have been thinking, do we really need to check all the contents of this file into git? Most of it is pretty much dev environment _artefacts_ that shouldn't really be committed anyway

How can we tell if a hApp was using a custom template though if cloning from an existing repo? Probably the presence of the `.scaffoldrc` file in the the `.templates/my-happ/.scaffoldrc` file would be a good indicator, which would suggest that this would be the only file we'd need to check into git from the template for the hApp

I could see the format for this file looking something like this now (pseudocode):

```
git = "https://github.com/c12i/my-template"
version="1.0.0"
scaffold_version="0.2"
```

It appears that my approach ends up producing yet another manifest file 😅

**Comment by guillemcordoba** [comment]
Oh and I'm not against maintaining the current approach, it's just that I want to enable the nix based approach because I see it fixes all these limitations, and I would heavily use it. If other people want to use the current approach, that's totally fine to me as well.

**Comment by c12i** [comment]
> Do you want me to create a PR that refactors the templates path argument so that all commands accept it, and that is sufficient for the nix approach?

Yes please, feel free to create a PR for this, some docs on how to set this up would also be useful

**Comment by guillemcordoba** [comment]
@c12i I just put up a PR addressing this. It still a draft, but it's feature complete. Let me know what you think of it. If you don't want to merge in this approach of removing the `--templates-url` argument, you absolutely can work on that branch to re-add it. However, I'm unblocked, as I can just point to this `nixify` branch from my custom templates and everything already works on that side (wonders of nix!).
