### ISSUE TITLE
Please upgrade `@msgpack/msgpack`

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/scaffolding#221]
Scaffolded projects are getting 2.7.x, 2.8.0 is available and currently looks like it's going to be the last version of that library. I'm not sure how important this is, but looking at npmjs.org, 2.8.0 is getting far more downloads than previous versions so that probably makes it a good choice.

This would be both for the tests and the UI. I'm using this version in my happ without issues, though I'm sure the scaffolding tests would catch any serialisation issues too!

**Comment by c12i** [comment]
Good find @ThetaSinner we can definitely update to `2.8.0`, glad you haven't encountered any issues yet, will do further testing when I migrate to this version though

**Comment by ThetaSinner** [comment]
I have some concerns about the maintenance of that library which is why I say it's probably the last version in the 2.x series for it. They certainly aren't responding to issues rapidly. Anyhow, we may as well be on the latest version with any improvements that have been made :)
