### ISSUE TITLE
make dependent collections reactive

### ISSUE THREAD

**Issue by pdaoust** [holochain/scaffolding#222]
The getting started guide on the Dev Portal instructs devs to create a comment type, which has a reference to a post hash. Then they're instructed to add `CreateComment` and `CommentsForPost` components to the `Post` component.

Adding a post updates the `AllPosts` collection view reactively, but adding a comment to a post doesn't update the `CommentsForPost` collection reactively. Right now I've just got a warning about that in the guide.

I wonder if this is a hard limitation of Svelte, a soft limitation because we simply haven't attended to this yet, or something else? I also wonder if it's common to all three of our front-end implementations?

**Comment by c12i** [comment]
> Right now I've just got a warning about that in the guide

@pdaoust I noticed this too, not only on svelte I think, the reason is because there are no `signal` event listeners for the `CommentsForPost` components, I can add the listener in the templates it's missing from to reactively have the newly inserted comment show up

**Comment by pdaoust** [comment]
that would be fantastic; thank you. I don't know enough about the codebase to know the correct remedy, so I'm glad you do :) I'm guessing this happens below the level of a particular front-end library?

**Comment by c12i** [comment]
> I'm guessing this happens below the level of a particular front-end library?

Not really, this is something that can be handled on the client side as far as I understand, it's how the linked PR above addresses the issue
