### ISSUE TITLE
[Feature] Link-types from AnyLinkableHash to AnyLinkableHash

### ISSUE THREAD

**Issue by matthme** [holochain/scaffolding#254]
Currently `hc scaffold link-type` only allows to create links from entry types to entry types, each of which must already have been created. A link in general however can point from an `AnyLinkableHash` to an `AnyLinkableHash`. A common use case for me is for example to make a link to or from an `AgentPublicKey`, I would like to have that be supported.

**Comment by c12i** [comment]
@matthme I guess this issue can still be closed by #380?

**Comment by matthme** [comment]
Yes I think so.
