### ISSUE TITLE
Unmaintained dependency `degit`

### ISSUE THREAD

**Issue by ThetaSinner** [holochain/scaffolding#319]
This dependency has some seriously old dependencies itself. The main problem seems to be `mio` which comes with a bunch of dependencies that recent versions of `mio` do not.

I believe the build problems I'm currently having are due to a problem on my system, but they drew my attention to this dependency. It looks like it'd be worth trying to get hold of the maintainer or forking the crate.

**Comment by c12i** [comment]
Thanks for the catch @ThetaSinner, fortunately `degit` is no longer in use for `0.3` and `weekly`. I assume you detected these issues on `0.2` or `0.1`?

**Comment by ThetaSinner** [comment]
Ahh sweet! Yes this was on `develop-0.2`. I was trying to reproduce a build error that somebody saw on the getting started guide. I got a different error that went away and I think was network related. Great, if this is gone from 0.3+ then we don't need this issue. Thank you for taking a look :)
