### ISSUE TITLE
[FEATURE] Bump lit version in lit template

### ISSUE THREAD

**Issue by matthme** [holochain/scaffolding#408]
Bump the lit template to lit version 3.x. It is currently using lit 2.6.

This would mean replacing:
```
    "@lit-labs/context": "^0.2.0",
    "@lit-labs/task": "^2.0.0",
    "lit": "^2.6.1"
```
with
```
    "lit": "^3.1.0",
    "@lit/context": "^1.1.0",
    "@lit/task": "^1.0.0",
```
Although I think `"@lit/task": "^1.0.0"` is not even used anywhere so it can potentially get removed completely.

It may also require smaller code changes but nothing major I think.

**Comment by c12i** [comment]
Cool, I have updated to the latest versions and moved `context` and `task` from `-labs` with #407 

I don't think we can removed `@lit/task` just yet, `Task` is still in use [here](https://github.com/holochain/scaffolding/pull/407/files#diff-6d3a9c82b7af56c052135695f51edfc6b0ba3213a1b2a8d621525511ea425316) for example

**Comment by matthme** [comment]
Oh cool, great :)

> I don't think we can removed @lit/task just yet, Task is still in use [here](https://github.com/holochain/scaffolding/pull/407/files#diff-6d3a9c82b7af56c052135695f51edfc6b0ba3213a1b2a8d621525511ea425316) for example

Okay, I did not see this, let's just keep it then.
