### ISSUE TITLE
npm run package fails to build .webhapp unless "skipLibCheck": true on tsconfig.json inside ui folder

### ISSUE THREAD

**Issue by tommycp3** [holochain/scaffolding#48]
I'm just playing around with the scaffold.

and I fail to build the .webhapp file and get this error.
![2022-11-24_10-51-37](https://user-images.githubusercontent.com/13199826/203670536-b010b863-7f45-43ae-8793-cc1a310e1c5f.png)

After a little searching I found an option to skip the library check on @bable/types.

By adding: 
`"skipLibCheck": true`
to the tsconfig.json file inside the ui directory.

Not sure if you want to update the scaffold to include this setting on the tsconfig.json so just documenting the issue here for you to process.

And if it's not need for other people why do I have to do this?

**Comment by c12i** [comment]
Not reproducible, closing
