### ISSUE TITLE
holochain_scaffolding_cli - Cannot add zome to a repository with an unexpected ui folder structure

### ISSUE THREAD

**Issue by matthme** [holochain/scaffolding#49]
Attempting to add a zome to an existing repo with a ui folder structure other than the one generated with the scaffolding tool fails although `hc-scaffold zome` does not seem to affect the `package.json` anyway:

```
$ ~/code/holochain/lightningrodlabs/we$ hc-scaffold zome
Error: Path was not found: ui/package.json
```

**Comment by guillemcordoba** [comment]
Nice!

**Comment by guillemcordoba** [comment]
Should be fixed in 0.0.4: https://crates.io/crates/holochain_scaffolding_cli

**Comment by matthme** [comment]
I get a few steps further now but still get stuck:
```
$ hc-scaffold zome
✔ Choose UI framework: · Lit
✔ What do you want to scaffold? · Integrity/coordinator zome-pair (recommended)
✔ Enter coordinator zome name (snake_case):
 (The integrity zome will automatically be named '{name of coordinator zome}_integrity')
 · group_lobby
Error: YAML serialization error: missing field `origin_time`

Caused by:
    missing field `origin_time`
``

**Comment by matthme** [comment]
Maybe the format of my origin time is [wrong/unexpected](https://github.com/lightningrodlabs/we/blob/050a13806c7592b28d1a7042bff7465ce13406bb/dnas/we/workdir/dna.yaml#L7)?

**Comment by guillemcordoba** [comment]
Yeah that *seems* to be the case... Let me see
