### ISSUE TITLE
Collections cannot (ergonomically) be sorted by a property of the Records

### ISSUE THREAD

**Issue by matthme** [holochain/scaffolding#57]
With the current pattern of only returning hashes instead of records from the backend and then the frontend pattern being like [this](https://github.com/holochain/scaffolding/blob/c8af11149875151b7100b88d6a9cb68d8ebfcff2/templates/lit/collection/ui/src/%7B%7Bdna_role_name%7D%7D/%7B%7Bcoordinator_zome_manifest.name%7D%7D/%7B%7Bkebab_case%20collection_name%7D%7D.ts.hbs#L41) it is not possible to sort entries in the UI by properties of their records (for example creation time or any property of the entry or derived from it) without quite extensive rewriting of the generated UI code.

Maybe that's something that's outweighed by other advantages of the current pattern but it's probably worth having a closer look at whether there are better patterns.

**Comment by guillemcordoba** [comment]
Hum I would say that if you want sorted collections then using the existing collections are not really the way to go... Or we may add sorting mechanisms on the backend one day, but I do not think that sorting should be done in the frontend really.

**Comment by guillemcordoba** [comment]
Should be fixed in the newest versions.
