### ISSUE TITLE
Call to google API's breaks offline behavior

### ISSUE THREAD

**Issue by matthme** [holochain/scaffolding#71]
Do we really need [this](https://github.com/holochain/scaffolding/blob/d118a337ad311049f36dd990a02e775b2cc0f05d/templates/lit/web-app/ui/index.html.hbs#L12) call to a CDN? I would prefer if the scaffolding tool's default templates were offline-first. Currently if an app with the scaffolding tool is opened offline, the screen turns blank until name resolution times out.

![image](https://user-images.githubusercontent.com/36768177/219946541-5716697e-621a-4420-a23a-7f49dcdf26e6.png)

**Comment by guillemcordoba** [comment]
Oh good point. Thanks

**Comment by c12i** [comment]
Closed since we have moved away from using material icons

**Comment by matthme** [comment]
I just noticed that there is still this one reference left: https://github.com/holochain/scaffolding/blob/ab7e7050abe4d28d45e1c1f5d8506a0368c0e30f/templates/custom-template/custom-template/template/web-app/ui/index.html.hbs#L12

**Comment by c12i** [comment]
Ahh, the `custom-template` is still using the older lit template. This is a template I have actually considered moving out of the repository or building it from from existing templates. Having to maintain this alongside the existing templates adds on top of the already existing effort in maintaining hbs templates. Tracking this here https://github.com/holochain/Components/issues/62
