### ISSUE TITLE
Scaffolding config

### ISSUE THREAD

**Issue by jmday** [holochain/scaffolding#77]
It would be so clutch to create a scaffold config that can be edited and then passed back into `hc scaffold` as a param so it creates all the things… and users don’t have to go back through all the questions again.

I found myself running the scaffolding tool multiple times for the same app after needing a minor change or just wanting to try again with a different option. It would be really really helpful to have some sort of config that can be edited then passed for a re-run.

**Comment by matthme** [comment]
I made similar experiences. It is quite cumbersome to rerun the scaffolding again and if the application is somewhat complex it's not easy to remember every step again. I would also welcome a solution along the lines you described.

**Comment by jamestolley** [comment]
I'm creating a tool to do this:

https://github.com/jamestolley/holochain-scaffold-runner

It's in the early stages but is already very useful (at least for me). I'd love feedback

**Comment by matthme** [comment]
Wow, that's pretty cool!

**Comment by c12i** [comment]
Closing this issue. It's currently getting tracked here (https://github.com/holochain/scaffolding/issues/392) for future implementation
