### ISSUE TITLE
convenience tweeks

### ISSUE THREAD

**Issue by nphias** [holochain/scaffolding#79]
so in the readme it tells you to do: 
`nix-shell http://holochain.love`   
that takes you down an hour long "love hole"

faster way is : 
 `nix run github:holochain/holochain#hc-scaffold -- example forum`

secondly when you have scaffolded "the quick way"
there is no way to see what version of scaffold has been used
would be helpful if that was included in one of the text/script files

**Comment by nphias** [comment]
answering the second part to my own question..  and leaving open for any comments

I prefer the `nix run` way as it means you will always use the latest scaffold version without having to do repeated global installs
if you want to see which version you have just used to scaffold files (or before you scaffold files):
`nix run github:holochain/holochain#hc-scaffold -- --version`

**Comment by guillemcordoba** [comment]
Hey @nphias , you were right, the holochain core team is moving away from holochain love, I updated the readme with your comments. Thanks :hugs:
