### ISSUE TITLE
Failed to load resource: .launcher-env.json (the server responded with a status of 404)

### ISSUE THREAD

**Issue by dcts** [holochain/scaffolding#8]
I tried to follow and recreate the scaffolding example from @guillemcordoba [tutorial video](https://www.youtube.com/watch?v=WzIcJpsznK4) (great video btw!). I chose the exact same settings and zome/dna definitions from the video. Everything seemed to work but when I run `npm run start` or `npm run network 3` I am not able to create wiki pages, the `create` button is greyed out. 
![Bildschirmfoto vom 2022-05-21 13-57-09](https://user-images.githubusercontent.com/44790691/169650546-700df463-8a96-4206-8831-52ad0c11f7d5.png)

I suspect it has something to do with the console error I got, somehow it can't load the browser polyfil:
```bash
Failed to load resource: the server responded with a status of 404 (Not Found)
```

Screenshot:
![Bildschirmfoto vom 2022-05-21 13-51-45](https://user-images.githubusercontent.com/44790691/169650496-ec2b7e3d-78c1-406b-9643-ce18722c39d3.png)

**Comment by guillemcordoba** [comment]
Hey @dcts thanks for the feedback :) 

Mmm is it also greyed out when you put some text in the content field?

**Comment by dcts** [comment]
@guillemcordoba yes it is greyed out also when I type text into the field.

**Comment by guillemcordoba** [comment]
Mmm I can't reproduce your issue... What version of the scaffolding tools are you using? You may wanna try `npx @holochain/create@latest` to get the latest version. If this doesn't fix it I may wanna jump in a call and debug the issue with you.

**Comment by dcts** [comment]
@guillemcordoba I did it again with the latest scaffolding tool but still the exact same issue persists. 
That would be awesome, thanks! You can book a meeting anytime that works for you: https://calendly.com/thomas-liist/30min
