### ISSUE TITLE
[feat] scaffolding of headless apps

### ISSUE THREAD

**Issue by matthme** [holochain/scaffolding#80]
It would be nice if there were an option to explicitly scaffold a headless app (i.e. without UI). Currently one is forced to select a UI framework and have UI components generated in any case and then must delete the UI folder manually. It's merely a question of convenience though.

**Comment by guillemcordoba** [comment]
mmm so that would be a job for a custom template. Should be easy enough to build one without UI, using https://docs.rs/holochain_scaffolding_cli/0.1.6/holochain_scaffolding_cli/#how-to-create-a-custom-template

**Comment by matthme** [comment]
I thought as well about creating a custom template. But I think it's a use case that's frequent enough that it may deserve built-in support. Because templates are not easily discoverable by new developers.

**Comment by matthme** [comment]
Maybe a solution could be to have a github repo with officially recommended templates that the scaffolding tool would display in the CLI? Could also be useful to integrate more UI frameworks from templates created by the community.

**Comment by guillemcordoba** [comment]
Oh I understand. I think it's best that people start creating their own custom templates, and if one of them is actually used around, then we contemplate pulling it in as built-in templates. Your idea about officially recommended templates makes me go "but that's so similar to built-in templates, we might as well pull them as built-in templates".

**Comment by c12i** [comment]
hey @guillemcordoba how about having an option to allow skipping generation of ui components for the scli commands that do this? This doesn't solve the issue of having to use the hard coded UI framework but would skip generating the UI folders

WDYT?

**Comment by guillemcordoba** [comment]
I think it should be it's own command. Right now we have:

```
hc scaffold web-app
hc scaffold dna
hc scaffold zome
hc scaffold entry-type
hc scaffold link-type
hc scaffold collection
```

To me, it seems really weird that `hc scaffold web-app` has a no UI option, I'd rather have a `hc scaffold app` command for that.

**Comment by c12i** [comment]
Yes, I can see how this option would be cumbersome.

I like the idea of `hc scaffold app` but it would be doing almost the same thing `hc scaffold web-app` already does right?

I am now seeing that using a custom template would be a much simpler workaround to this, though I think these are templates we should provide ourselves
