### ISSUE TITLE
[feat] reactjs template

### ISSUE THREAD

**Issue by dcts** [holochain/scaffolding#81]
Are there plans to integrat reactjs? :)

**Comment by guillemcordoba** [comment]
I don't have any plans for that right now, but you can go ahead and create your own custom template using [this](https://docs.rs/holochain_scaffolding_cli/0.1.6/holochain_scaffolding_cli/#how-to-create-a-custom-template). Let me know if you build a custom template for react and we'll probably add it as a built-in template :)

**Comment by nick-stebbings** [comment]
I am working on one and will be looking for testers in the near future.
Currently has Create, Edit, Details and All  components. I am about 80% done I reckon.

https://github.com/nick-stebbings/holochain-react-scaffold-template

**Comment by dcts** [comment]
Thats awesome @nick-stebbings , happy to test so feel free to post here. 👍

**Comment by nick-stebbings** [comment]
@dcts @guillemcordoba 

I am pleased to say I have finally finished and can basically scaffold a happ in my sleep by this point haha.

Check it out:
`hc scaffold web-app forum --templates-url https://github.com/nick-stebbings/holochain-react-scaffold-template`

And please lodge any issues in my repo for now. There will be a few (haven't implemented Option yet, for instance) but hopefully the scaffold is pretty complete.
Specifically needs testing by willing folks:
- ByAuthor collection components
- Signal handling (didn't test at all I just copied from the Vue template)

**Comment by guillemcordoba** [comment]
@robbiecarlton :100:
